// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCz6rixYGtDeWKXNfSDpfVubSvCJr6x-c',
    appId: '1:664379036921:web:bc38582c82ec62655e7e28',
    messagingSenderId: '664379036921',
    projectId: 'gutkasahib-1ab82',
    authDomain: 'gutkasahib-1ab82.firebaseapp.com',
    storageBucket: 'gutkasahib-1ab82.appspot.com',
    measurementId: 'G-ZBPZNWQM6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH2Zs2Qkq6YGLNN2Iwn7Cf5AjiPk6cw48',
    appId: '1:664379036921:android:5c08c7f6e337b9d05e7e28',
    messagingSenderId: '664379036921',
    projectId: 'gutkasahib-1ab82',
    storageBucket: 'gutkasahib-1ab82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClvJtJ2k5DY4o0NyBnVE8-BR53UP2hHTE',
    appId: '1:664379036921:ios:dd3ddd525ca4ee345e7e28',
    messagingSenderId: '664379036921',
    projectId: 'gutkasahib-1ab82',
    storageBucket: 'gutkasahib-1ab82.appspot.com',
    iosBundleId: 'com.example.sundarGutka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClvJtJ2k5DY4o0NyBnVE8-BR53UP2hHTE',
    appId: '1:664379036921:ios:dd3ddd525ca4ee345e7e28',
    messagingSenderId: '664379036921',
    projectId: 'gutkasahib-1ab82',
    storageBucket: 'gutkasahib-1ab82.appspot.com',
    iosBundleId: 'com.example.sundarGutka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCz6rixYGtDeWKXNfSDpfVubSvCJr6x-c',
    appId: '1:664379036921:web:a986935183dc23a35e7e28',
    messagingSenderId: '664379036921',
    projectId: 'gutkasahib-1ab82',
    authDomain: 'gutkasahib-1ab82.firebaseapp.com',
    storageBucket: 'gutkasahib-1ab82.appspot.com',
    measurementId: 'G-M9YV3F19NV',
  );
}
